language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - "coverage run --source='.' -p flake8 --exclude "*versions*" ."
  - "coverage run --source='.' -p python -m unittest"

after_success:
  - coverage combine
  - coveralls
